export enum EUserStatus {
  PENDING = 'PENDING',
  MISSING_MAIL = 'MISSING_MAIL',
  VERIFY_MAIL = 'VERIFY_MAIL',
  MISSING_NAME = 'MISSING_NAME',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum ERole {
  ADMIN = 'ADMIN',
  USER = 'USER',
}
